import Head from 'next/head'
import Footer from '../../components/Common/Footer'
import Blogs from '../../components/TodosBlogs/Blogs'

export default function Blog() {
  return(
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Blogs />
    </main>
    <Footer />
  </>
  )
}