import Head from 'next/head'
import Menu from '../../components/Common/Menu'
import Enterprises from '../../components/Enterprises/Enterprises'

const Empreendimentos = () => {
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu />
        <Enterprises />
      </main>
    </>
  )
}

export default Empreendimentos