import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../../components/Common/Header'
import Opportunity from '../../components/Home/Opportunity'
import Release from '../../components/Home/Release'
import Media from '../../components/Home/Media'
import Footer from '../../components/Common/Footer'
import Search from '../../components/Common/Search'
import Instagram from '../../components/TodosImoveis/Instagram'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Search />
        <Opportunity />
        <Release />
        <Instagram />
        <Media />
      </main>
      <Footer />
    </>
  )
}
