import Head from 'next/head'
import About from '../../components/About/About'
import Menu from '../../components/Common/Menu'

const Sobre = () => {
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu />
        <About/>
      </main>
    </>
  )
}

export default Sobre