import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '../../components/Header'
import Search from '../../components/Search'
import AllImoveis from '../../components/TodosImoveis/AllImoveis'
import GuideInvestor from '../../components/TodosImoveis/GuideInvestor'
import Instagram from '../../components/TodosImoveis/Instagram'
import Footer from '../../components/Footer'

export default function TodosImoveis() {
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Search />
        <AllImoveis />
        <GuideInvestor />
        <Instagram />
        <Footer />
      </main>
    </>
  )
}