import Head from 'next/head'
import Blog from '../../../components/Blog/Blog'
import Menu from '../../../components/Common/Menu'
import Footer from '../../../components/Common/Footer'


export default function BlogUnico() {
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu />
        <Blog />
        <Footer />
      </main>
    </>
  )
}